export const ALL_ITEMS = 'ALL_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const REDACT_ITEM = 'REDACT_ITEM'
export const FILTER_ITEMS = 'FILTER_ITEMS'
export const DRAGGBLE_ITEMS = 'DRAGGBLE_ITEMS'
